#!/bin/bash

# 本脚本用于查看最后一个出错退出的任务的错误输出。
# 默认使用vim打开，可以在下方的Default Arguments中修改用于打开文件的程序。
# TODO: 加入通过任务名打开的功能。
# TODO: 支持用户自定义的错误输出文件夹。
# NOTE: 尽管目前脚本支持使用单个参数指定查看倒数第n个被修改的文件，但该逻辑将在
#       未来被删除。
#
# 脚本原理：
#     通过`ls -t stderr`对修改时间排序，打开最新被修改的文件。

set -euo pipefail

###### Default Arguments ######
editor_exe="vim"
n=1
###############################

if ! [ -d stderr ]; then
    echo "ERROR: Directory 'stderr' not found. Make sure you are in the work directory." >&2
    exit 1
fi

if [ $# -gt 0 ]; then
    n=${1}
    int_regexp='^[1-9][0-9]*$'
    if ! [[ ${n} =~ ${int_regexp} ]]; then
        echo "ERROR: '${n}' is not an integer." >&2
        exit 1
    fi
fi

filename=`ls -t stderr | grep "^[1-9][0-9]*\.txt$" | head -n ${n} | tail -n 1`

if [ -z "${filename}" ]; then
    echo "No available stderr file." >&2
    exit 1
fi

${editor_exe} stderr/${filename}

