#!/bin/bash

# 本脚本用于查看历史任务信息，基于`submit`脚本生成的`~/.slurm_job_history`文件。
#
# 脚本使用示例：
#     hist
#     查看最后10个任务。
#     hist 50
#     查看最后50个任务。

set -euo pipefail

###### Default Arguments ######
n=10
###############################

if [ $# -gt 0 ]; then
    n=${1}
    int_regexp='^[1-9][0-9]*$'
    if ! [[ ${n} =~ ${int_regexp} ]]; then
        echo "ERROR: Number of records '${n}' is not an integer." >&2
        exit 1
    fi
fi

tail -n ${n} ~/.slurm_job_history

