#!/bin/bash

# 本脚本用于移除文件名或目录名中以点号分隔的第一个后缀名。
# 等价于命令'mv xxx.suffix xxx'。
# 与本脚本对应的脚本为app，用于添加后缀名。
#
# 脚本使用示例：
#     rma exp/train_a.lr1e-3 exp/train_b.lr1e-3 exp/train_c.lr1e-3
#     以上命令将exp/train_a.lr1e-3等三个文件夹中的".lr1e-3"后缀名去除。
#
# 参数：
#     -f 或 --force：强制修改，即若修改后的名称与已有文件/目录冲突，则覆盖之。

set -euo pipefail

help_message="\
    用于移除文件名或目录名中以点号分隔的第一个后缀名。
    等价于命令'mv xxx.suffix xxx'。
    与本脚本对应的脚本为app，用于添加后缀名。

参数:
    -f 或 --force：强制修改，即若修改后的名称与已有文件/目录冲突，则覆盖之。

示例：
    rma exp/train_a.lr1e-3 exp/train_b.lr1e-3 exp/train_c.lr1e-3
"

if [ $# -le 0 ]; then
    echo "${help_message}"
    exit 0
fi

# Some flags
force=false # flag to control if the target can be overwritten

# We use getopt to parse options.
args=$(getopt -l "help,force" -o "hf" -- "$@")
if [ $? != 0 ]; then # there are some errors in the arguments
    echo "ERROR: Some arguments cannot be recognized. Are there any arguments mistaken?" >&2
    exit 1
fi
eval set -- "$args" # rearrange the arguments to a format that can be processed easily

# Parse arguments. The error checking is done after.
while [ $# -ge 1 ]; do
    case "$1" in
        --)
            shift
            break
            ;;
        -h|--help)
            echo "${help_message}"
            exit 0
            ;;
        -f|--force)
            force=true
            shift
            ;;
    esac
done

for f; do # bash 'for' iterate "$@" by default
    if ! [ -e "${f}" ]; then
        echo "WARNING: File '${f}' doesn't exist. Skipped." >&2
        continue
    fi
    suffix=${f##*.}
    if [ "${suffix}" = "${f}" ]; then
        echo "WARNING: File '${f}' doesn't have a suffix. Skipped." >&2
        continue
    fi
    newname=${f:0:${#f}-${#suffix}-1}
    if [ -e "${newname}" -a "${force}" = "false" ]; then
        echo "WARNING: File '${newname}' exists. Skipped." >&2
        continue
    fi
    mv -f ${f} ${newname}
done

