#!/bin/bash

# Remove a suffix from the name of some files and directories.
# Equivalent to 'mv xxx.suffix xxx'.

set -euo pipefail

if [ $# -lt 1 ]; then
    echo "ERROR: Too few arguments." >&2
    exit 1
fi

for f; do # bash 'for' iterate "$@" by default
    if ! [ -e "${f}" ]; then
        echo "WARNING: File '${f}' doesn't exist. Skipped." >&2
        continue
    fi
    suffix=${f##*.}
    if [ "${suffix}" = "${f}" ]; then
        echo "WARNING: File '${f}' doesn't have a suffix. Skipped." >&2
        continue
    fi
    newname=${f:0:${#f}-${#suffix}-1}
    if [ -e "${newname}" ]; then
        echo "WARNING: File '${newname}' exists. Skipped." >&2
        continue
    fi
    mv ${f} ${newname}
done

